name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: Avinash415
          output: snake.svg

      - name: Commit and Push Snake Animation
        run: |
          git config --local user.email "avinash843117kumar@gmail.com"
          git config --local user.name "GitHub Actions"
          git add snake.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push
